//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace CaseInfoSystem.WordAddIn
{
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name = "FullTrust")]
    public sealed partial class ThisAddIn : Microsoft.Office.Tools.AddInBase
    {
        internal Microsoft.Office.Interop.Word.Application Application;
        internal Microsoft.Office.Tools.CustomTaskPaneCollection CustomTaskPanes;
        internal Microsoft.Office.Tools.SmartTagCollection VstoSmartTags;

        public ThisAddIn(global::Microsoft.Office.Tools.Word.ApplicationFactory factory, global::System.IServiceProvider serviceProvider)
            : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Globals.Factory = factory;
        }

        protected override void Initialize()
        {
            base.Initialize();
            Application = GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisAddIn = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            InitializeCachedData();
            InitializeControls();
            InitializeComponents();
            InitializeData();
        }

        protected override void FinishInitialization()
        {
            InternalStartup();
            OnStartup();
        }

        protected override void InitializeDataBindings()
        {
            BeginInitialization();
            BindToData();
            EndInitialization();
        }

        private void InitializeCachedData()
        {
            if (DataHost == null)
            {
                return;
            }

            if (DataHost.IsCacheInitialized)
            {
                DataHost.FillCachedData(this);
            }
        }

        private void InitializeData()
        {
        }

        private void BindToData()
        {
        }

        private void BeginInitialization()
        {
            BeginInit();
            CustomTaskPanes.BeginInit();
            VstoSmartTags.BeginInit();
        }

        private void EndInitialization()
        {
            VstoSmartTags.EndInit();
            CustomTaskPanes.EndInit();
            EndInit();
        }

        private void InitializeControls()
        {
            CustomTaskPanes = Globals.Factory.CreateCustomTaskPaneCollection(null, null, "CustomTaskPanes", "CustomTaskPanes", this);
            VstoSmartTags = Globals.Factory.CreateSmartTagCollection(null, null, "VstoSmartTags", "VstoSmartTags", this);
        }

        private void InitializeComponents()
        {
        }

        protected override void OnShutdown()
        {
            VstoSmartTags.Dispose();
            CustomTaskPanes.Dispose();
            base.OnShutdown();
        }
    }

    internal sealed partial class Globals
    {
        private Globals()
        {
        }

        private static ThisAddIn _thisAddIn;
        private static global::Microsoft.Office.Tools.Word.ApplicationFactory _factory;
        private static ThisRibbonCollection _thisRibbonCollection;

        internal static ThisAddIn ThisAddIn
        {
            get { return _thisAddIn; }
            set
            {
                if (_thisAddIn == null)
                {
                    _thisAddIn = value;
                    return;
                }

                throw new global::System.NotSupportedException();
            }
        }

        internal static global::Microsoft.Office.Tools.Word.ApplicationFactory Factory
        {
            get { return _factory; }
            set
            {
                if (_factory == null)
                {
                    _factory = value;
                    return;
                }

                throw new global::System.NotSupportedException();
            }
        }

        internal static ThisRibbonCollection Ribbons
        {
            get
            {
                if (_thisRibbonCollection == null)
                {
                    _thisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }

                return _thisRibbonCollection;
            }
        }
    }

    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase
    {
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory)
            : base(factory)
        {
        }
    }
}
