name: CI Tests

on:
  push:
  pull_request:

jobs:
  pure-tests:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore pure test project
        working-directory: dev/CaseInfoSystem.Tests
        run: dotnet restore

      - name: Build pure test project
        working-directory: dev/CaseInfoSystem.Tests
        run: dotnet build -c Release --no-restore

      - name: Run pure tests
        working-directory: dev/CaseInfoSystem.Tests
        run: dotnet test -c Release --no-build
